/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type CalculationResponse = { 'ok' : CalculationResult } |
  { 'err' : string };
export interface CalculationResult { 'value' : number, 'steps' : Array<string> }
export interface _SERVICE {
  'ohmsLaw' : ActorMethod<
    [[] | [number], [] | [number], [] | [number]],
    CalculationResponse
  >,
  'rcTimeConstant' : ActorMethod<[number, number], CalculationResponse>,
  'rlcResonantFrequency' : ActorMethod<[number, number], CalculationResponse>,
  'voltageDivider' : ActorMethod<[number, number, number], CalculationResponse>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];