/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CalculationResult = IDL.Record({
  'value' : IDL.Float64,
  'steps' : IDL.Vec(IDL.Text),
});
export const CalculationResponse = IDL.Variant({
  'ok' : CalculationResult,
  'err' : IDL.Text,
});

export const idlService = IDL.Service({
  'ohmsLaw' : IDL.Func(
      [IDL.Opt(IDL.Float64), IDL.Opt(IDL.Float64), IDL.Opt(IDL.Float64)],
      [CalculationResponse],
      [],
    ),
  'rcTimeConstant' : IDL.Func(
      [IDL.Float64, IDL.Float64],
      [CalculationResponse],
      [],
    ),
  'rlcResonantFrequency' : IDL.Func(
      [IDL.Float64, IDL.Float64],
      [CalculationResponse],
      [],
    ),
  'voltageDivider' : IDL.Func(
      [IDL.Float64, IDL.Float64, IDL.Float64],
      [CalculationResponse],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CalculationResult = IDL.Record({
    'value' : IDL.Float64,
    'steps' : IDL.Vec(IDL.Text),
  });
  const CalculationResponse = IDL.Variant({
    'ok' : CalculationResult,
    'err' : IDL.Text,
  });
  
  return IDL.Service({
    'ohmsLaw' : IDL.Func(
        [IDL.Opt(IDL.Float64), IDL.Opt(IDL.Float64), IDL.Opt(IDL.Float64)],
        [CalculationResponse],
        [],
      ),
    'rcTimeConstant' : IDL.Func(
        [IDL.Float64, IDL.Float64],
        [CalculationResponse],
        [],
      ),
    'rlcResonantFrequency' : IDL.Func(
        [IDL.Float64, IDL.Float64],
        [CalculationResponse],
        [],
      ),
    'voltageDivider' : IDL.Func(
        [IDL.Float64, IDL.Float64, IDL.Float64],
        [CalculationResponse],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };